### ISSUE TITLE
Dead IPv4 Atlanta Speed Test Mirror

### ISSUE THREAD

**Issue by hidden-refuge** [sohamb03/bench-sh#1]
The Atlanta IPv4 Speed Test mirror server seems to be dead.

**Comment by hidden-refuge** [comment]
I have been looking for a replacement by the way but all I found were dead links to other Atlanta servers. I'd suggest to replace it with a mirror close to Atlanta but in another state.

**Comment by sohamb03** [comment]
Thanks for reporting the issue @hidden-refuge. It has been fixed and replaced with a Atlanta SpeedTest server of my own. :-)
